# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use an official Node.js image as a base
FROM node:20-alpine AS build

# Set the working directory
WORKDIR /app

# Copy the package.json and package-lock.json
COPY package*.json ./

# Install dependencies without running scripts
RUN npm install --ignore-scripts

# Copy the rest of the application code
COPY . .

# Build the application
RUN npm run build

# Use a lightweight Node.js image for the runtime
FROM node:20-alpine

# Set the working directory
WORKDIR /app

# Copy the built files and the node_modules
COPY --from=build /app/build /app/build
COPY --from=build /app/node_modules /app/node_modules
COPY --from=build /app/package.json /app/package.json

# Set the environment variable for GitHub token
ENV GITHUB_TOKEN=your-github-token

# Expose port if necessary (not specified in the README)
# EXPOSE 3000

# Run the application
CMD ["node", "build/index.js"]
